name: Publish to NuGet

on:
  push:
    tags: "v[0-9]+.[0-9]+.[0-9]+-?*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Create version from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Print detected version
      run: echo ${{ env.VERSION }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack --configuration Release -p:PackageVersion=${{ env.VERSION }} --output ${{ env.DOTNET_ROOT }}/myapp

    - name: Push to NuGet
      run: find ${{ env.DOTNET_ROOT }}/myapp/*.nupkg -type f -exec dotnet nuget push '{}' --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} \;
